### PR TITLE
Ct/additional core rulesets

### PR DESCRIPTION
**Pull request by Buruko**

### CODE REVIEW

**Comment by jimconner** [comment]
8 commits, but it says 0 files changed at the top. Have all of these changes already been incorporated by other PRs?

**Comment by Buruko** [comment]
I believe so, but I want to merge the branch cause I can't work on my fork til I pull from orendain/DemeoMods/main and it says I have a conflict.

**Comment by Buruko** [comment]
I found and fixed an error in a Ruleset, 1 file changed.

**Comment by jimconner** [comment]
There will be a better way of solving this than this PR. Let's find a way to get your local git history in order rather than adding needless commits to `main`. The commit history becomes really important a few years down the road when you start doing git-archaeology to find out why things are a particular way.

**Comment by Buruko** [comment]
Understood. Let me know how I can help.

**Comment by Buruko** [comment]
Re-opened to publish NoSurprises Ruleset fix.

**Pull request closed without merging**
